import type { TwinModel } from '@twinforge/shared';

export const MODELS: TwinModel[] = [
  // ── Human Models (20) ───────────────────────────────────────────────────────
  {
    id: 'hm-adult-male-25',
    name: 'Adult Male — 25y',
    category: 'human',
    complexity: 'MED',
    geometryType: 'human-default',
    description: 'Healthy adult male baseline. Optimal cardiovascular and metabolic markers. Primary reference model for performance and wellness simulations.',
    tags: ['baseline', 'cardiovascular', 'metabolic', 'wellness'],
    vertexCount: 12840,
    polygonCount: 24200,
    organSystems: ['cardiovascular', 'musculoskeletal', 'respiratory', 'metabolic'],
    simulationCompatibility: ['stress-test', 'nutrition', 'aging', 'performance'],
  },
  {
    id: 'hm-adult-male-35',
    name: 'Adult Male — 35y',
    category: 'human',
    complexity: 'MED',
    geometryType: 'human-default',
    description: 'Mid-career adult male. Early-stage metabolic risk indicators. Optimal for workplace health and preventive care simulations.',
    tags: ['baseline', 'preventive', 'metabolic-risk', 'workplace'],
    vertexCount: 12840,
    polygonCount: 24200,
    organSystems: ['cardiovascular', 'musculoskeletal', 'metabolic', 'hepatic'],
    simulationCompatibility: ['metabolic-syndrome', 'stress-test', 'nutrition', 'aging'],
  },
  {
    id: 'hm-adult-male-50',
    name: 'Adult Male — 50y',
    category: 'human',
    complexity: 'HIGH',
    geometryType: 'human-default',
    description: 'Mid-life adult male with age-related comorbidity risk. Suitable for cardiovascular, oncological, and metabolic risk projections.',
    tags: ['comorbidity', 'cardiovascular-risk', 'aging', 'preventive'],
    vertexCount: 13200,
    polygonCount: 25100,
    organSystems: ['cardiovascular', 'musculoskeletal', 'metabolic', 'renal', 'prostate'],
    simulationCompatibility: ['mi-risk', 'diabetes-onset', 'cognitive-decline', 'cancer-screening'],
  },
  {
    id: 'hm-adult-male-65',
    name: 'Adult Male — 65y+',
    category: 'human',
    complexity: 'HIGH',
    geometryType: 'human-default',
    description: 'Senior male model with multi-system age-related changes. High-fidelity geriatric simulation and medication impact modelling.',
    tags: ['geriatric', 'polypharmacy', 'frailty', 'cardiovascular'],
    vertexCount: 13200,
    polygonCount: 25100,
    organSystems: ['cardiovascular', 'renal', 'musculoskeletal', 'cognitive', 'metabolic'],
    simulationCompatibility: ['polypharmacy', 'fall-risk', 'cognitive-decline', 'cardiac-event'],
  },
  {
    id: 'hm-adult-female-25',
    name: 'Adult Female — 25y',
    category: 'human',
    complexity: 'MED',
    geometryType: 'human-default',
    description: 'Healthy young adult female baseline. Hormonal cycle integration. Optimal for reproductive health and sports performance simulations.',
    tags: ['baseline', 'reproductive', 'hormonal', 'wellness'],
    vertexCount: 12640,
    polygonCount: 23800,
    organSystems: ['cardiovascular', 'reproductive', 'musculoskeletal', 'metabolic'],
    simulationCompatibility: ['stress-test', 'nutrition', 'hormonal-cycle', 'performance'],
  },
  {
    id: 'hm-adult-female-35',
    name: 'Adult Female — 35y',
    category: 'human',
    complexity: 'MED',
    geometryType: 'human-default',
    description: 'Mid-life adult female. Pre-menopausal hormonal transitions. Suitable for cardiovascular and metabolic risk modelling.',
    tags: ['pre-menopausal', 'cardiovascular', 'metabolic', 'hormonal'],
    vertexCount: 12640,
    polygonCount: 23800,
    organSystems: ['cardiovascular', 'reproductive', 'metabolic', 'hepatic'],
    simulationCompatibility: ['autoimmune', 'thyroid', 'metabolic-syndrome', 'nutrition'],
  },
  {
    id: 'hm-adult-female-50',
    name: 'Adult Female — 50y',
    category: 'human',
    complexity: 'HIGH',
    geometryType: 'human-default',
    description: 'Peri-menopausal female model. Cardiovascular risk elevation, bone density changes. Rich comorbidity simulation capability.',
    tags: ['peri-menopausal', 'osteoporosis-risk', 'cardiovascular', 'hormonal'],
    vertexCount: 13000,
    polygonCount: 24600,
    organSystems: ['cardiovascular', 'skeletal', 'metabolic', 'cognitive', 'reproductive'],
    simulationCompatibility: ['menopause', 'osteoporosis', 'cardiovascular-event', 'medication-impact'],
  },
  {
    id: 'hm-adult-female-65',
    name: 'Adult Female — 65y+',
    category: 'human',
    complexity: 'HIGH',
    geometryType: 'human-default',
    description: 'Senior female model. Post-menopausal risk profile, frailty index integration. Geriatric and palliative care scenarios.',
    tags: ['geriatric', 'post-menopausal', 'frailty', 'polypharmacy'],
    vertexCount: 13000,
    polygonCount: 24600,
    organSystems: ['cardiovascular', 'skeletal', 'renal', 'cognitive', 'metabolic'],
    simulationCompatibility: ['fall-risk', 'cognitive-decline', 'polypharmacy', 'cardiac-event'],
  },
  {
    id: 'hm-athletic',
    name: 'Athletic Profile',
    category: 'human',
    complexity: 'HIGH',
    geometryType: 'human-athletic',
    description: 'Elite athletic build with peak cardiovascular and musculoskeletal performance markers. Sports medicine and performance optimisation simulations.',
    tags: ['elite', 'cardiovascular', 'musculoskeletal', 'performance', 'VO2max'],
    vertexCount: 15200,
    polygonCount: 28400,
    organSystems: ['cardiovascular', 'musculoskeletal', 'respiratory', 'metabolic'],
    simulationCompatibility: ['overtraining', 'injury-risk', 'altitude', 'heat-stress'],
  },
  {
    id: 'hm-cardiac-patient',
    name: 'Cardiac Patient',
    category: 'human',
    complexity: 'ULTRA',
    geometryType: 'human-cardiac',
    description: 'Heart condition variant with documented comorbidities. Multi-drug regimen, reduced ejection fraction. Cardiology and emergency medicine use cases.',
    tags: ['cardiac', 'heart-failure', 'comorbidity', 'medication', 'arrhythmia'],
    vertexCount: 16800,
    polygonCount: 31200,
    organSystems: ['cardiovascular', 'renal', 'hepatic', 'respiratory', 'metabolic'],
    simulationCompatibility: ['arrhythmia', 'mi-risk', 'heart-failure', 'medication-interaction'],
  },
  {
    id: 'hm-post-surgical',
    name: 'Post-Surgical Patient',
    category: 'human',
    complexity: 'ULTRA',
    geometryType: 'human-surgical',
    description: 'Recovery phase model post-major surgery. Wound healing dynamics, medication regimen, physiotherapy protocol integration.',
    tags: ['post-surgical', 'recovery', 'rehabilitation', 'medication', 'wound-healing'],
    vertexCount: 16400,
    polygonCount: 30100,
    organSystems: ['cardiovascular', 'immunological', 'metabolic', 'musculoskeletal'],
    simulationCompatibility: ['recovery', 'infection-risk', 'rehabilitation', 'medication-impact'],
  },
  {
    id: 'hm-child-8',
    name: 'Child — 8y',
    category: 'human',
    complexity: 'MED',
    geometryType: 'human-child',
    description: 'Paediatric model 8-year-old. Growth trajectory, developing organ systems. Paediatric dosing and developmental milestone simulations.',
    tags: ['pediatric', 'developmental', 'growth', 'immunological'],
    vertexCount: 11200,
    polygonCount: 20800,
    organSystems: ['cardiovascular', 'musculoskeletal', 'immunological', 'neurological', 'metabolic'],
    simulationCompatibility: ['growth', 'vaccination', 'infection', 'nutrition'],
  },
  {
    id: 'hm-child-12',
    name: 'Child — 12y',
    category: 'human',
    complexity: 'MED',
    geometryType: 'human-child',
    description: 'Pre-adolescent paediatric model. Onset of hormonal changes, peak growth velocity. Adolescent health and sports medicine applications.',
    tags: ['pediatric', 'pre-adolescent', 'growth-spurt', 'musculoskeletal'],
    vertexCount: 11800,
    polygonCount: 22000,
    organSystems: ['cardiovascular', 'musculoskeletal', 'reproductive', 'neurological', 'metabolic'],
    simulationCompatibility: ['puberty', 'sports-injury', 'nutrition', 'mental-health'],
  },

  // ── Industrial Models (15) ───────────────────────────────────────────────────
  {
    id: 'ind-gas-turbine',
    name: 'Gas Turbine',
    category: 'industrial',
    complexity: 'ULTRA',
    geometryType: 'turbine',
    description: 'High-performance industrial gas turbine. Blade erosion, thermal cycling, and combustion efficiency degradation modelling. Offshore and onshore variants.',
    tags: ['power-generation', 'thermal', 'blade-erosion', 'combustion', 'offshore'],
    vertexCount: 48200,
    polygonCount: 92400,
    industry: 'Power Generation / Oil & Gas',
    sensorCount: 84,
    failureModes: ['blade-fouling', 'hot-gas-path-erosion', 'bearing-failure', 'compressor-surge', 'seal-degradation'],
    maintenanceInterval: '8,000 hours',
  },
  {
    id: 'ind-wind-turbine',
    name: 'Wind Turbine',
    category: 'industrial',
    complexity: 'HIGH',
    geometryType: 'turbine',
    description: '2.5MW horizontal-axis wind turbine. Blade fatigue, gearbox wear, and icing event simulation. Nordic wind farm applications.',
    tags: ['renewable', 'wind', 'blade-fatigue', 'gearbox', 'nordic'],
    vertexCount: 38400,
    polygonCount: 72100,
    industry: 'Renewable Energy',
    sensorCount: 56,
    failureModes: ['blade-icing', 'gearbox-wear', 'main-bearing-failure', 'pitch-system-fault', 'yaw-error'],
    maintenanceInterval: '6 months',
  },
  {
    id: 'ind-cnc-milling',
    name: 'CNC Milling Machine',
    category: 'industrial',
    complexity: 'HIGH',
    geometryType: 'cnc-machine',
    description: '5-axis CNC milling centre. Tool wear, spindle vibration, and thermal drift compensation modelling. Precision manufacturing quality prediction.',
    tags: ['manufacturing', 'precision', 'tool-wear', 'vibration', 'thermal-drift'],
    vertexCount: 32100,
    polygonCount: 61200,
    industry: 'Manufacturing',
    sensorCount: 42,
    failureModes: ['tool-breakage', 'spindle-bearing-wear', 'thermal-deformation', 'coolant-failure', 'axis-misalignment'],
    maintenanceInterval: '500 hours',
  },
  {
    id: 'ind-robot-arm',
    name: '6-Axis Robotic Arm',
    category: 'industrial',
    complexity: 'HIGH',
    geometryType: 'robot-arm',
    description: 'Industrial 6-axis collaborative robot arm. Joint stress, torque overload, and encoder drift simulation. Assembly line and welding applications.',
    tags: ['robotics', 'automation', 'joint-stress', 'torque', 'welding'],
    vertexCount: 28600,
    polygonCount: 54800,
    industry: 'Manufacturing / Automation',
    sensorCount: 38,
    failureModes: ['joint-overload', 'encoder-drift', 'gearbox-backlash', 'motor-overheating', 'cable-fatigue'],
    maintenanceInterval: '10,000 cycles',
  },
  {
    id: 'ind-conveyor',
    name: 'Conveyor Belt System',
    category: 'industrial',
    complexity: 'MED',
    geometryType: 'conveyor',
    description: 'Heavy-duty conveyor belt for bulk material handling. Belt tear, roller failure, throughput degradation, and jam scenario modelling.',
    tags: ['logistics', 'bulk-handling', 'belt-wear', 'roller-failure', 'throughput'],
    vertexCount: 18400,
    polygonCount: 34200,
    industry: 'Logistics / Mining / Manufacturing',
    sensorCount: 24,
    failureModes: ['belt-tear', 'roller-seizure', 'belt-misalignment', 'motor-overload', 'jam-event'],
    maintenanceInterval: '2,000 hours',
  },
  {
    id: 'ind-hydraulic-press',
    name: 'Hydraulic Press',
    category: 'industrial',
    complexity: 'MED',
    geometryType: 'hydraulic-press',
    description: '500-tonne hydraulic press. Seal degradation, pressure cycle fatigue, and hydraulic fluid contamination simulation.',
    tags: ['metalforming', 'hydraulic', 'seal-degradation', 'pressure-fatigue', 'stamping'],
    vertexCount: 22800,
    polygonCount: 43600,
    industry: 'Metal Forming / Automotive',
    sensorCount: 28,
    failureModes: ['seal-failure', 'hydraulic-leak', 'pressure-fluctuation', 'cylinder-scoring', 'valve-wear'],
    maintenanceInterval: '1,000 hours',
  },
  {
    id: 'ind-offshore-pump',
    name: 'Offshore Pump Assembly',
    category: 'industrial',
    complexity: 'ULTRA',
    geometryType: 'offshore-pump',
    description: 'Subsea injection pump assembly. Corrosion modelling, cavitation simulation, and seal integrity under high-pressure offshore conditions.',
    tags: ['offshore', 'subsea', 'corrosion', 'cavitation', 'high-pressure', 'Norway'],
    vertexCount: 44200,
    polygonCount: 86400,
    industry: 'Oil & Gas / Offshore',
    sensorCount: 62,
    failureModes: ['impeller-cavitation', 'shaft-seal-failure', 'bearing-corrosion', 'casing-erosion', 'motor-winding-fault'],
    maintenanceInterval: '4,000 hours',
  },
  {
    id: 'ind-centrifugal-pump',
    name: 'Centrifugal Pump',
    category: 'industrial',
    complexity: 'MED',
    geometryType: 'pump',
    description: 'Industrial centrifugal pump for process fluid handling. Wear ring degradation, impeller erosion, and NPSH margin simulation.',
    tags: ['process', 'fluid-handling', 'impeller-erosion', 'wear-ring', 'NPSH'],
    vertexCount: 19600,
    polygonCount: 37200,
    industry: 'Process / Chemical / Water Treatment',
    sensorCount: 22,
    failureModes: ['impeller-wear', 'seal-leakage', 'bearing-failure', 'cavitation', 'recirculation'],
    maintenanceInterval: '3,000 hours',
  },
  {
    id: 'ind-heat-exchanger',
    name: 'Shell & Tube Heat Exchanger',
    category: 'industrial',
    complexity: 'HIGH',
    geometryType: 'cnc-machine',
    description: 'Industrial shell-and-tube heat exchanger. Fouling progression, tube corrosion, and thermal efficiency degradation modelling.',
    tags: ['thermal', 'process', 'fouling', 'corrosion', 'efficiency'],
    vertexCount: 26400,
    polygonCount: 50800,
    industry: 'Process / Petrochemical',
    sensorCount: 18,
    failureModes: ['tube-fouling', 'tube-corrosion', 'shell-vibration', 'baffle-erosion', 'thermal-fatigue'],
    maintenanceInterval: '2 years',
  },
  {
    id: 'ind-compressor',
    name: 'Reciprocating Compressor',
    category: 'industrial',
    complexity: 'ULTRA',
    geometryType: 'offshore-pump',
    description: 'High-pressure reciprocating gas compressor. Valve failure, piston ring wear, and rod load limit simulation. Oil & gas and industrial gas applications.',
    tags: ['compression', 'gas', 'valve-failure', 'piston-wear', 'high-pressure'],
    vertexCount: 41800,
    polygonCount: 80200,
    industry: 'Oil & Gas / Industrial Gas',
    sensorCount: 54,
    failureModes: ['valve-failure', 'piston-ring-wear', 'connecting-rod-failure', 'crosshead-wear', 'cylinder-overheating'],
    maintenanceInterval: '8,000 hours',
  },
];

export const HUMAN_MODELS = MODELS.filter(m => m.category === 'human');
export const INDUSTRIAL_MODELS = MODELS.filter(m => m.category === 'industrial');

export function getModelById(id: string): TwinModel | undefined {
  return MODELS.find(m => m.id === id);
}

export const COMPLEXITY_ORDER: Record<string, number> = { LOW: 0, MED: 1, HIGH: 2, ULTRA: 3 };
