import type { ScenarioPreset } from '@twinforge/shared';

export const SCENARIOS: ScenarioPreset[] = [
  // ── Human Scenarios (30) ────────────────────────────────────────────────────

  // Cardiovascular
  {
    id: 'hs-stress-test',
    name: 'Cardiac Stress Test',
    description: 'Simulates a graded exercise stress test. Tracks ECG changes, ST-segment shifts, blood pressure response, and arrhythmia risk through peak exertion and recovery.',
    category: 'cardiovascular',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '45-minute protocol',
    tags: ['cardio', 'exercise', 'ECG', 'arrhythmia'],
  },
  {
    id: 'hs-arrhythmia',
    name: 'Arrhythmia Event',
    description: 'Models onset, progression, and resolution of atrial fibrillation. Includes haemodynamic impact, thromboembolism risk cascade, and cardioversion scenarios.',
    category: 'cardiovascular',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '6-hour episode',
    tags: ['AFib', 'arrhythmia', 'haemodynamic', 'stroke-risk'],
  },
  {
    id: 'hs-mi-risk',
    name: 'Myocardial Infarction Risk',
    description: 'Projects probability and timeline of myocardial infarction over 5 years based on biomarker trajectory, lifestyle factors, and genetic risk weighting.',
    category: 'cardiovascular',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '5-year projection',
    tags: ['MI', 'STEMI', 'risk-projection', 'biomarkers'],
  },
  {
    id: 'hs-post-surgical-cardiac',
    name: 'Post-Surgical Cardiac Recovery',
    description: 'Models myocardial recovery following CABG or valve replacement. Ejection fraction trajectory, medication titration, and rehabilitation protocol outcomes.',
    category: 'cardiovascular',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '90-day recovery',
    tags: ['CABG', 'recovery', 'ejection-fraction', 'rehabilitation'],
  },
  {
    id: 'hs-heart-failure',
    name: 'Heart Failure Progression',
    description: 'Simulates NYHA class progression in heart failure. Fluid retention dynamics, medication response, and hospitalisation risk windows.',
    category: 'cardiovascular',
    twinCategory: 'human',
    estimatedRisk: 'CRITICAL',
    durationLabel: '12-month projection',
    tags: ['heart-failure', 'NYHA', 'fluid-retention', 'diuretics'],
  },
  {
    id: 'hs-hypertension-crisis',
    name: 'Hypertensive Crisis',
    description: 'Models rapid blood pressure escalation to hypertensive urgency / emergency. End-organ damage timeline and acute intervention protocols.',
    category: 'cardiovascular',
    twinCategory: 'human',
    estimatedRisk: 'CRITICAL',
    durationLabel: '24-hour acute episode',
    tags: ['hypertension', 'end-organ', 'stroke-risk', 'emergency'],
  },

  // Metabolic
  {
    id: 'hs-diabetic-episode',
    name: 'Diabetic Hypoglycaemic Episode',
    description: 'Simulates rapid blood glucose drop below threshold. Counter-regulatory hormone cascade, cognitive impairment timeline, and recovery trajectory.',
    category: 'metabolic',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '2-hour episode',
    tags: ['diabetes', 'hypoglycaemia', 'glucose', 'insulin'],
  },
  {
    id: 'hs-weight-loss',
    name: 'Rapid Weight Loss Protocol',
    description: 'Models physiological response to aggressive caloric deficit. Lean mass preservation, hormonal adaptation, resting metabolic rate trajectory.',
    category: 'metabolic',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '12-week protocol',
    tags: ['weight-loss', 'caloric-deficit', 'metabolism', 'body-composition'],
  },
  {
    id: 'hs-nutrition-opt',
    name: 'Nutrition Optimisation',
    description: 'Predicts optimal macronutrient ratio for the twin\'s metabolic phenotype. Biomarker trajectory under multiple dietary interventions.',
    category: 'metabolic',
    twinCategory: 'human',
    estimatedRisk: 'LOW',
    durationLabel: '6-week simulation',
    tags: ['nutrition', 'macros', 'biomarkers', 'metabolism'],
  },
  {
    id: 'hs-metabolic-syndrome',
    name: 'Metabolic Syndrome Onset',
    description: 'Projects timeline to full metabolic syndrome criteria. Insulin resistance progression, visceral adiposity, and cardiovascular risk amplification.',
    category: 'metabolic',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '3-year projection',
    tags: ['metabolic-syndrome', 'insulin-resistance', 'visceral-fat', 'cardiovascular'],
  },
  {
    id: 'hs-type2-onset',
    name: 'Type 2 Diabetes Onset',
    description: 'Models progression from insulin resistance to overt Type 2 diabetes. Beta-cell exhaustion timeline and intervention window identification.',
    category: 'metabolic',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '5-year projection',
    tags: ['T2DM', 'beta-cell', 'insulin-resistance', 'HbA1c'],
  },

  // Neurological
  {
    id: 'hs-sleep-deprivation',
    name: 'Sleep Deprivation Cascade',
    description: 'Simulates 72-hour sleep restriction. Cognitive performance degradation, cortisol dysregulation, immune suppression, and cardiovascular strain.',
    category: 'neurological',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '72-hour simulation',
    tags: ['sleep', 'cognition', 'cortisol', 'immune'],
  },
  {
    id: 'hs-chronic-stress',
    name: 'Chronic Stress Response',
    description: 'Models allostatic load accumulation over 6 months. HPA axis dysregulation, cardiovascular impact, and mental health risk trajectory.',
    category: 'neurological',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '6-month simulation',
    tags: ['stress', 'cortisol', 'HPA-axis', 'burnout'],
  },
  {
    id: 'hs-cognitive-decline',
    name: 'Cognitive Decline Projection',
    description: 'Projects cognitive function trajectory over 10 years. Neuroinflammation markers, grey matter volume, and intervention sensitivity analysis.',
    category: 'neurological',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '10-year projection',
    tags: ['dementia', 'cognition', 'neuroinflammation', 'Alzheimer'],
  },

  // Environmental
  {
    id: 'hs-heat-exposure',
    name: 'Extreme Heat Exposure',
    description: 'Simulates occupational or environmental heat stress. Core temperature rise, dehydration cascade, heat stroke risk threshold, and hydration protocol optimisation.',
    category: 'environmental',
    twinCategory: 'human',
    estimatedRisk: 'HIGH',
    durationLabel: '8-hour exposure',
    tags: ['heat-stress', 'dehydration', 'core-temperature', 'occupational'],
  },
  {
    id: 'hs-altitude',
    name: 'High-Altitude Adaptation',
    description: 'Models acclimatisation response to 3,500m altitude. Haematological adaptations, AMS risk, VO2max decrement, and expedition readiness score.',
    category: 'environmental',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '14-day acclimatisation',
    tags: ['altitude', 'AMS', 'haematology', 'VO2max', 'expedition'],
  },
  {
    id: 'hs-pandemic-exposure',
    name: 'Pandemic Exposure Modelling',
    description: 'Simulates immune response to novel respiratory pathogen. Severity prediction based on comorbidity profile, vaccine status, and ACE2 expression model.',
    category: 'environmental',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '21-day illness trajectory',
    tags: ['infectious-disease', 'immune-response', 'respiratory', 'severity'],
  },

  // Aging
  {
    id: 'hs-aging-5yr',
    name: '5-Year Biological Aging',
    description: 'Projects multi-system biological age progression over 5 years. Telomere dynamics, organ reserve decline, and lifestyle modification impact.',
    category: 'aging',
    twinCategory: 'human',
    estimatedRisk: 'LOW',
    durationLabel: '5-year projection',
    tags: ['aging', 'longevity', 'telomeres', 'organ-reserve'],
  },
  {
    id: 'hs-medication-impact',
    name: 'Medication Impact Simulation',
    description: 'Models pharmacokinetic and pharmacodynamic effects of a multi-drug regimen. Drug-drug interactions, side effect timeline, and efficacy trajectory.',
    category: 'aging',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '6-month treatment',
    tags: ['pharmacology', 'polypharmacy', 'PK/PD', 'side-effects'],
  },
  {
    id: 'hs-cancer-screening',
    name: 'Cancer Risk Projection',
    description: 'Calculates age-adjusted cancer incidence probability based on twin\'s biomarker profile, lifestyle, and family history. Screening interval optimisation.',
    category: 'aging',
    twinCategory: 'human',
    estimatedRisk: 'MEDIUM',
    durationLabel: '10-year risk window',
    tags: ['oncology', 'screening', 'genetic-risk', 'prevention'],
  },

  // ── Industrial Scenarios (30) ────────────────────────────────────────────────

  // Mechanical failure
  {
    id: 'is-bearing-wear',
    name: 'Bearing Wear Progression',
    description: 'Models progressive rolling element bearing degradation from incipient defect to spalling failure. Vibration signature evolution and RUL (Remaining Useful Life) estimation.',
    category: 'mechanical-failure',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '2,000-hour simulation',
    tags: ['bearing', 'vibration', 'RUL', 'spalling', 'predictive-maintenance'],
  },
  {
    id: 'is-shaft-misalignment',
    name: 'Shaft Misalignment',
    description: 'Simulates angular and parallel misalignment effects on bearing load, vibration harmonics, seal wear, and coupling fatigue.',
    category: 'mechanical-failure',
    twinCategory: 'industrial',
    estimatedRisk: 'MEDIUM',
    durationLabel: '500-hour simulation',
    tags: ['alignment', 'vibration', 'coupling', 'seal'],
  },
  {
    id: 'is-seal-degradation',
    name: 'Seal Degradation Timeline',
    description: 'Models elastomeric seal hardening, compression set, and leakage onset under thermal cycling and chemical exposure. Maintenance window prediction.',
    category: 'mechanical-failure',
    twinCategory: 'industrial',
    estimatedRisk: 'MEDIUM',
    durationLabel: '1,000-hour simulation',
    tags: ['seal', 'leakage', 'elastomer', 'thermal-cycling'],
  },
  {
    id: 'is-gearbox-wear',
    name: 'Gearbox Tooth Wear',
    description: 'Simulates micropitting and macropitting tooth flank wear under varying load cycles. Oil film analysis, metal particle count trajectory.',
    category: 'mechanical-failure',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '5,000-hour simulation',
    tags: ['gearbox', 'micropitting', 'oil-analysis', 'tooth-wear'],
  },
  {
    id: 'is-blade-erosion',
    name: 'Turbine Blade Erosion',
    description: 'Models leading-edge erosion of turbine blades from particulate impact. Efficiency degradation curve, hot-section inspection interval optimisation.',
    category: 'mechanical-failure',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '8,000-hour service life',
    tags: ['turbine', 'blade', 'erosion', 'efficiency', 'hot-section'],
  },

  // Thermal events
  {
    id: 'is-overheating',
    name: 'Overheating Cascade',
    description: 'Simulates loss of cooling leading to progressive overheating. Component temperature exceedance sequence, material property changes, and shutdown threshold.',
    category: 'thermal',
    twinCategory: 'industrial',
    estimatedRisk: 'CRITICAL',
    durationLabel: '4-hour incident',
    tags: ['overheating', 'cooling-failure', 'thermal-runaway', 'safety'],
  },
  {
    id: 'is-thermal-fatigue',
    name: 'Thermal Fatigue Cycle',
    description: 'Models material fatigue from repeated thermal cycling. Crack initiation site prediction, Coffin-Manson life estimation.',
    category: 'thermal',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '10,000-cycle simulation',
    tags: ['thermal-fatigue', 'crack-initiation', 'Coffin-Manson', 'life-estimation'],
  },
  {
    id: 'is-coolant-failure',
    name: 'Coolant System Failure',
    description: 'Simulates loss of coolant flow. Heat soak trajectory, component temperature peaks, safe shutdown sequence, and restart protocol.',
    category: 'thermal',
    twinCategory: 'industrial',
    estimatedRisk: 'CRITICAL',
    durationLabel: '2-hour incident',
    tags: ['coolant', 'heat-soak', 'shutdown', 'restart'],
  },

  // Operational stress
  {
    id: 'is-overload',
    name: 'Overload Event',
    description: 'Models effects of operational overload (125% rated capacity). Stress concentration mapping, fatigue life consumption rate, and structural margin erosion.',
    category: 'operational-stress',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '8-hour overload event',
    tags: ['overload', 'stress', 'fatigue-life', 'structural'],
  },
  {
    id: 'is-emergency-stop',
    name: 'Emergency Stop Cycle',
    description: 'Simulates repeated emergency stop events. Braking force impulse, component shock loading, and cumulative fatigue damage index.',
    category: 'operational-stress',
    twinCategory: 'industrial',
    estimatedRisk: 'MEDIUM',
    durationLabel: '100-cycle simulation',
    tags: ['e-stop', 'shock', 'braking', 'fatigue-damage'],
  },
  {
    id: 'is-resonance',
    name: 'Vibration Resonance Test',
    description: 'Sweeps operating speed through resonance frequencies. Identifies critical speed zones, structural response peaks, and vibration isolation requirements.',
    category: 'operational-stress',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '4-hour sweep test',
    tags: ['resonance', 'critical-speed', 'vibration', 'structural-response'],
  },

  // Maintenance
  {
    id: 'is-run-to-failure',
    name: 'Run-to-Failure Analysis',
    description: 'Compares run-to-failure cost vs. predictive maintenance ROI. Failure mode probability weighting, downtime cost model, and optimal intervention point.',
    category: 'maintenance',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: 'Full lifecycle analysis',
    tags: ['RCM', 'predictive-maintenance', 'ROI', 'downtime-cost', 'FMEA'],
  },
  {
    id: 'is-predictive-maintenance',
    name: 'Predictive Maintenance ROI',
    description: 'Calculates optimal condition-based maintenance intervals. Sensor data quality assessment, false positive rate, and net present value of PdM programme.',
    category: 'maintenance',
    twinCategory: 'industrial',
    estimatedRisk: 'LOW',
    durationLabel: '3-year programme',
    tags: ['PdM', 'CBM', 'sensor', 'ROI', 'interval-optimisation'],
  },
  {
    id: 'is-inspection-interval',
    name: 'Inspection Interval Optimisation',
    description: 'Risk-based inspection (RBI) analysis. Failure probability vs. consequence matrix, optimal inspection frequency, and NDE method recommendation.',
    category: 'maintenance',
    twinCategory: 'industrial',
    estimatedRisk: 'LOW',
    durationLabel: 'Annual planning cycle',
    tags: ['RBI', 'inspection', 'NDE', 'risk-matrix', 'consequence'],
  },

  // Corrosion / Environmental
  {
    id: 'is-corrosion-offshore',
    name: 'Offshore Corrosion Modelling',
    description: 'Models electrochemical corrosion under seawater immersion and splash zone conditions. Wall thickness reduction trajectory, cathodic protection efficiency.',
    category: 'corrosion',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '5-year exposure',
    tags: ['corrosion', 'offshore', 'cathodic-protection', 'seawater', 'Norway'],
  },
  {
    id: 'is-arctic-cycling',
    name: 'Arctic Temperature Cycling',
    description: 'Simulates material performance under Arctic thermal cycling (-40°C to +20°C). Brittle fracture risk, seal failure probability, and lubricant performance.',
    category: 'corrosion',
    twinCategory: 'industrial',
    estimatedRisk: 'HIGH',
    durationLabel: '1-year arctic season',
    tags: ['arctic', 'brittle-fracture', 'cold', 'lubricant', 'nordic'],
  },
];

export const HUMAN_SCENARIOS = SCENARIOS.filter(s => s.twinCategory === 'human');
export const INDUSTRIAL_SCENARIOS = SCENARIOS.filter(s => s.twinCategory === 'industrial');

export function getScenarioById(id: string): ScenarioPreset | undefined {
  return SCENARIOS.find(s => s.id === id);
}

export function getScenariosForCategory(category: 'human' | 'industrial'): ScenarioPreset[] {
  return SCENARIOS.filter(s => s.twinCategory === category);
}
