import type { SimulationReport } from '@twinforge/shared';
import RiskBadge from './RiskBadge';

const PRIORITY_COLOR: Record<string, string> = {
  immediate: 'text-danger border-danger/30 bg-danger/5',
  'short-term': 'text-warning border-warning/30 bg-warning/5',
  'long-term': 'text-accent border-accent/30 bg-accent/5',
};

const RISK_TIMELINE_COLOR: Record<string, string> = {
  LOW: 'bg-success',
  MEDIUM: 'bg-warning',
  HIGH: 'bg-danger',
  CRITICAL: 'bg-danger',
};

interface ReportRendererProps {
  report: SimulationReport;
}

export default function ReportRenderer({ report }: ReportRendererProps) {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="card-elevated">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <RiskBadge level={report.overallRisk} size="lg" />
              <span className="text-xs text-txt-muted">Overall Risk Assessment</span>
            </div>
            <h1 className="text-xl font-bold text-txt-primary">{report.scenarioName}</h1>
            <p className="text-sm text-txt-muted mt-1">Twin: <span className="text-txt-secondary font-medium">{report.twinName}</span></p>
          </div>
          <div className="text-right shrink-0">
            <p className="text-[10px] text-txt-muted">Generated by</p>
            <p className="text-xs font-medium text-accent">{report.modelUsed}</p>
            <p className="text-[10px] text-txt-muted mt-1">
              {new Date(report.generatedAt).toLocaleDateString('en-GB', { dateStyle: 'medium' })}
            </p>
          </div>
        </div>

        <div className="mt-4 pt-4 border-t border-border">
          <p className="section-title mb-2">Executive Summary</p>
          <p className="text-sm text-txt-secondary leading-relaxed">{report.executiveSummary}</p>
        </div>
      </div>

      {/* Timeline */}
      {report.phases.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-txt-primary mb-4">Simulation Timeline</h2>
          <div className="space-y-3">
            {report.phases.map((phase, idx) => (
              <div key={idx} className="flex gap-4">
                {/* Timeline connector */}
                <div className="flex flex-col items-center shrink-0">
                  <div className={`w-3 h-3 rounded-full ${RISK_TIMELINE_COLOR[phase.riskLevel]} shrink-0 mt-1`} />
                  {idx < report.phases.length - 1 && (
                    <div className="w-px flex-1 bg-border mt-1" />
                  )}
                </div>

                <div className="card flex-1 mb-2">
                  <div className="flex items-center justify-between mb-2">
                    <div>
                      <span className="text-[10px] text-txt-muted font-mono">{phase.timeLabel}</span>
                      <h3 className="text-sm font-semibold text-txt-primary mt-0.5">{phase.title}</h3>
                    </div>
                    <RiskBadge level={phase.riskLevel} />
                  </div>
                  <p className="text-xs text-txt-secondary leading-relaxed">{phase.description}</p>

                  {phase.keyMetrics.length > 0 && (
                    <div className="flex flex-wrap gap-2 mt-3">
                      {phase.keyMetrics.map((metric, mi) => (
                        <div key={mi} className="bg-bg-base border border-border rounded px-2 py-1">
                          <p className="text-[10px] text-txt-muted">{metric.label}</p>
                          <p className="text-xs font-mono font-semibold text-txt-primary">{metric.value}</p>
                          {metric.delta && (
                            <p className={`text-[10px] font-mono ${metric.delta.startsWith('+') ? 'text-danger' : 'text-success'}`}>
                              {metric.delta}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Findings */}
      {report.findings.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-txt-primary mb-4">Key Findings</h2>
          <div className="space-y-3">
            {report.findings.map((finding, i) => (
              <div key={i} className="card border-l-2" style={{ borderLeftColor: finding.severity === 'CRITICAL' ? '#EF4444' : finding.severity === 'HIGH' ? '#EF4444' : finding.severity === 'MEDIUM' ? '#F59E0B' : '#10B981' }}>
                <div className="flex items-start gap-3">
                  <RiskBadge level={finding.severity} />
                  <div>
                    <p className="text-sm font-semibold text-txt-primary">{finding.title}</p>
                    <p className="text-xs text-txt-secondary leading-relaxed mt-1">{finding.detail}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Recommendations */}
      {report.recommendations.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-txt-primary mb-4">Recommendations</h2>
          <div className="space-y-3">
            {report.recommendations.map((rec, i) => (
              <div key={i} className={`border rounded-xl p-4 ${PRIORITY_COLOR[rec.priority]}`}>
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-[10px] font-bold uppercase tracking-wider opacity-70">{rec.priority}</span>
                </div>
                <p className="text-sm font-semibold text-txt-primary">{rec.action}</p>
                <p className="text-xs mt-1 opacity-80 leading-relaxed">{rec.rationale}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="text-center py-4 border-t border-border">
        <p className="text-[10px] text-txt-muted">
          Generated by TwinForge AI Engine · {report.modelUsed} · {new Date(report.generatedAt).toLocaleString()}
        </p>
        <p className="text-[10px] text-txt-disabled mt-1">
          For clinical or engineering decisions, consult qualified professionals. This simulation is for decision-support only.
        </p>
      </div>
    </div>
  );
}
